### PR TITLE
Fix session ending bugs

### LINKED ISSUE #121: Finishing a session crashes the program
Steps to recreate bug:
1. ```generate 3```
2. ```start```
3. ```finish```

No specific error message shown:
```
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-11.0.16.1\bin\java.exe'' finished with non-zero exit value 1
```
I think its something to do with NULL workouts when ending a session

### PR DESCRIPTION
**Pull request by EangJS**
Fix #121 bug

* There is a dupilicate ```endWorkout()``` method call which lead to a nullpointer exception as previous workout has been "saved" and deleted

* Also configure logger to provide messages > Level.WARNING

### CODE REVIEW

File: src/main/java/seedu/duke/logic/commandhandler/ExerciseSessionCommandHandler.java [hunk 1]
```diff
@@ -106,8 +106,6 @@ public void handleExerciseSessionUserCommands (String[] userCommands, Ui ui,
                 }
                 break;
             case FINISH_COMMAND:
```
Comment (L-K-Chng) [inline src/main/java/seedu/duke/logic/commandhandler/ExerciseSessionCommandHandler.java:108]: Good attention to detail

File: src/main/java/seedu/duke/storage/JsonUserPlansStorage.java [hunk 2]
```diff
@@ -56,16 +56,24 @@ public void writeToJson (UserPlan userPlan) throws DukeError {
...
+        UserPlan userPlan;
         try {
             userPlan = jsonUserPlansLoader.loadPlanFromJson(userPlansFilePath);
             logger.log(Level.INFO, "Plans Data has been restored from the previous session!");
             return userPlan;
         } catch (Exception e) {
-            logger.log(Level.WARNING, "Plans data file has been corrupted or missing, we will create a new file for " +
-                "you, all your plans will be lost.");
-            return userPlan;
+            userPlan = new UserPlan();
```
Comment (L-K-Chng) [inline src/main/java/seedu/duke/storage/JsonUserPlansStorage.java:65]: good improvement of logger

**Review by L-K-Chng — APPROVED** [review]
